/*
  _____ _ _ _                    _             _       
 |  ___(_) | |_ ___ _ __   _ __ | |_   _  __ _(_)_ __  
 | |_  | | | __/ _ \ '__| | '_ \| | | | |/ _` | | '_ \ 
 |  _| | | | ||  __/ |    | |_) | | |_| | (_| | | | | |
 |_|   |_|_|\__\___|_|    | .__/|_|\__,_|\__, |_|_| |_|
                          |_|            |___/         
# A Template for Postural_metrics_assessmentPlugin, a Filter Plugin
# Generated by the command: C:\Program Files\MADS\usr\local\bin\mads-plugin.exe -t filter -d C:\mirrorworld\postural_metrics_assessment -i C:\Program Files\MADS\usr\local\bin postural_metrics_assessment
# Hostname: unknown
# Current working directory: C:\mirrorworld\postural_metrics_assessment
# Creation date: 2025-10-08T10:39:22.525+0200
# NOTICE: MADS Version v1.3.2
*/
// Mandatory included headers
#include <filter.hpp>
#include <nlohmann/json.hpp>
#include <pugg/Kernel.h>

// other includes as needed here
#include <vector>
#include <array>
#include <Eigen/Dense>
#include <fstream>

// Define the name of the plugin
#ifndef PLUGIN_NAME
#define PLUGIN_NAME "postural_metrics_assessment"
#endif

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

// Load the namespaces
using namespace std;
using json = nlohmann::json;

std::vector<std::string> joint_map = { 
      "NOS_","NEC_","SHOR","ELBR","WRIR","SHOL","ELBL","WRIL",
      "HIPR","KNER","ANKR","HIPL","KNEL","ANKL",
      "EYER","EYEL","EARR","EARL"
    }; // default joint map 

// Plugin class. This shall be the only part that needs to be modified,
// implementing the actual functionality
class Postural_metrics_assessmentPlugin : public Filter<json, json> {

public:

  return_type compute_baricenter() {
    /*
    Compute the baricenter (center of mass) of the joint positions.
    TODO: Implement the actual computation logic. Current implementation is just the average of the joint positions.
    */

    if (_positions.empty()) {
      _error = "No joint positions available for center of mass computation.";
      return return_type::retry;
    }

    Eigen::Vector3d com = Eigen::Vector3d::Zero();
    for (const auto &pos : _positions) {
      com += pos;
    }
    com /= _positions.size();

    // Store the computed center of mass
    _com = com;
    return return_type::success;
  }

  return_type compute_horiz_reach() {
    /*
    Compute the horizontal reach.
    */

    // Compute the horizontal reach (left and right) using WRIR and WRIL joints
    // WRIR: right wrist, WRIL: left wrist

    // check if _com is valid
    if (_com == Eigen::Vector3d::Zero()) {
      _error = "Center of mass is not valid.";
      return return_type::retry;
    }

    int idx_wr_right = keypoints_map_string2int["WRIR"];
    int idx_wr_left = keypoints_map_string2int["WRIL"];

    // Check if wrist positions are valid
    if (_positions[idx_wr_right] == Eigen::Vector3d::Zero() || _positions[idx_wr_left] == Eigen::Vector3d::Zero()) {
      _error = "Wrist positions are not valid.";
      return return_type::retry;
    }

    double dx_r = _com[0] - _positions[idx_wr_right][0];
    double dz_r = _com[2] - _positions[idx_wr_right][2];
    _horiz_reach_right = std::sqrt(dx_r * dx_r + dz_r * dz_r);

    double dx_l = _com[0] - _positions[idx_wr_left][0];
    double dz_l = _com[2] - _positions[idx_wr_left][2];
    _horiz_reach_left = std::sqrt(dx_l * dx_l + dz_l * dz_l);

    return return_type::success;
  }

  return_type compute_vert_reach() {
    /*
    Compute the vertical reach.
    */

    int idx_elbr = keypoints_map_string2int["ELBR"];
    int idx_elbl = keypoints_map_string2int["ELBL"];
    int idx_shor = keypoints_map_string2int["SHOR"];
    int idx_shol = keypoints_map_string2int["SHOL"];
    int idx_nec  = keypoints_map_string2int["NEC_"];
    int idx_spc  = keypoints_map_string2int["SPC_"];

    // Check if required joint positions are valid
    if (_positions[idx_elbr] == Eigen::Vector3d::Zero() || _positions[idx_elbl] == Eigen::Vector3d::Zero() ||
        _positions[idx_shor] == Eigen::Vector3d::Zero() || _positions[idx_shol] == Eigen::Vector3d::Zero() ||
        _positions[idx_nec]  == Eigen::Vector3d::Zero() || _positions[idx_spc]  == Eigen::Vector3d::Zero()) {
      _error = "Required joint positions for vertical reach computation are not valid.";
      return return_type::retry;
    }

    // Compute vectors
    Eigen::Vector3d arm_r = _positions[idx_elbr] - _positions[idx_shor];
    Eigen::Vector3d arm_l = _positions[idx_elbl] - _positions[idx_shol];
    Eigen::Vector3d torso = _positions[idx_nec] - _positions[idx_spc];

    // Compute vertical reach right
    double dot_r = torso.dot(arm_r);
    double norm_torso = torso.norm();
    double norm_arm_r = arm_r.norm();
    if (norm_torso > 1e-6 && norm_arm_r > 1e-6) {
      double angle_r = std::acos(std::clamp(dot_r / (norm_torso * norm_arm_r), -1.0, 1.0));
      _vert_reach_right = static_cast<float>((M_PI - angle_r) * 180.0 / M_PI);
    } else {
      _vert_reach_right = 0.0f;
    }

    // Compute vertical reach left
    double dot_l = torso.dot(arm_l);
    double norm_arm_l = arm_l.norm();
    if (norm_torso > 1e-6 && norm_arm_l > 1e-6) {
      double angle_l = std::acos(std::clamp(dot_l / (norm_torso * norm_arm_l), -1.0, 1.0));
      _vert_reach_left = static_cast<float>((M_PI - angle_l) * 180.0 / M_PI);
    } else {
      _vert_reach_left = 0.0f;
    }

    return return_type::success;
  }

  return_type compute_cervical_flex() {
    /*
    Compute the cervical flexion.
    */

    // Compute cervical flexion angle using EARR, EARL, NOS_, NEC_, SPC_
    int idx_earr = keypoints_map_string2int["EARR"];
    int idx_earl = keypoints_map_string2int["EARL"];
    int idx_nos  = keypoints_map_string2int["NOS_"];
    int idx_nec  = keypoints_map_string2int["NEC_"];
    int idx_spc  = keypoints_map_string2int["SPC_"];

    // Check if required joint positions are valid
    if (_positions[idx_earr] == Eigen::Vector3d::Zero() ||
      _positions[idx_earl] == Eigen::Vector3d::Zero() ||
      _positions[idx_nos]  == Eigen::Vector3d::Zero() ||
      _positions[idx_nec]  == Eigen::Vector3d::Zero() ||
      _positions[idx_spc]  == Eigen::Vector3d::Zero()) {
      _error = "Required joint positions for cervical flexion computation are not valid.";
      return return_type::retry;
    }

    // Compute head vector: average(EARR, EARL, NOS_) - NEC_
    Eigen::Vector3d head_avg = (_positions[idx_earr] + _positions[idx_earl] + _positions[idx_nos]) / 3.0;
    Eigen::Vector3d head_vec = head_avg - _positions[idx_nec];

    // Compute torso vector: NEC_ - SPC_
    Eigen::Vector3d torso_vec = _positions[idx_nec] - _positions[idx_spc];

    // Compute angle between torso and head vectors
    double dot_val = torso_vec.dot(head_vec);
    double norm_torso = torso_vec.norm();
    double norm_head = head_vec.norm();

    if (norm_torso > 1e-6 && norm_head > 1e-6) {
      double angle = std::acos(std::clamp(dot_val / (norm_torso * norm_head), -1.0, 1.0));
      _cervical_flex = static_cast<float>(angle * 180.0 / M_PI);
    } else {
      _cervical_flex = 0.0f;
    }

    return return_type::success;
  }

  return_type compute_stability_margin() {
    /*
    Compute the stability margin.
    NOTE: This implementation assumes the presence of ankle and foot joints.
    If FOOR and FOOL joints are not available, only ANKR and ANKL are used.
    */

    int idx_ankr = keypoints_map_string2int["ANKR"];
    int idx_ankl = keypoints_map_string2int["ANKL"];
    int idx_foor = keypoints_map_string2int.count("FOOR") ? keypoints_map_string2int["FOOR"] : -1;
    int idx_fool = keypoints_map_string2int.count("FOOL") ? keypoints_map_string2int["FOOL"] : -1;

    // Check if required joints are valid
    if (_positions[idx_ankr] == Eigen::Vector3d::Zero() ||
      _positions[idx_ankl] == Eigen::Vector3d::Zero() ||
      (idx_foor >= 0 && _positions[idx_foor] == Eigen::Vector3d::Zero()) ||
      (idx_fool >= 0 && _positions[idx_fool] == Eigen::Vector3d::Zero())) {
      _error = "Required joint positions for stability margin computation are not valid.";
      return return_type::retry;
    }

    // Compute average feet position (x, z)
    std::vector<Eigen::Vector3d> feet_joints;
    feet_joints.push_back(_positions[idx_ankr]);
    feet_joints.push_back(_positions[idx_ankl]);
    if (idx_foor >= 0) feet_joints.push_back(_positions[idx_foor]);
    if (idx_fool >= 0) feet_joints.push_back(_positions[idx_fool]);

    Eigen::Vector2d feet_avg = Eigen::Vector2d::Zero();
    for (const auto& pos : feet_joints) {
      feet_avg[0] += pos[0];
      feet_avg[1] += pos[2];
    }
    feet_avg /= feet_joints.size();

    // COM x, z
    double com_x = _com[0];
    double com_z = _com[2];

    // Compute stability margin
    double dx = com_x - feet_avg[0];
    double dz = com_z - feet_avg[1];
    _stability_margin = static_cast<float>(std::sqrt(dx * dx + dz * dz));
    
    return return_type::success;
  }

   return_type compute_back_angles() {
    /*
    Compute the back angles.
    TODO: Implement the actual computation logic. Current implementation is just a print message.
    */

    int idx_hipr = keypoints_map_string2int["HIPR"];
    int idx_hipl = keypoints_map_string2int["HIPL"];
    int idx_spn = keypoints_map_string2int["SPN_"];
    int idx_spc = keypoints_map_string2int["SPC_"];
    int idx_nec = keypoints_map_string2int["NEC_"];
    int idx_shor = keypoints_map_string2int["SHOR"];
    int idx_shol = keypoints_map_string2int["SHOL"];

    // Check required joints
    if (_positions[idx_hipr] == Eigen::Vector3d::Zero() ||
      _positions[idx_hipl] == Eigen::Vector3d::Zero() ||
      _positions[idx_spn] == Eigen::Vector3d::Zero() ||
      _positions[idx_spc] == Eigen::Vector3d::Zero() ||
      _positions[idx_nec] == Eigen::Vector3d::Zero() ||
      _positions[idx_shor] == Eigen::Vector3d::Zero() ||
      _positions[idx_shol] == Eigen::Vector3d::Zero()) {
      _error = "Required joint positions for back angle computation are not valid.";
      return return_type::retry;
    }

    // torso = average(NEC_, SPC_, SPN_) - average(HIPL, HIPR)
    Eigen::Vector3d avg_upper = (_positions[idx_nec] + _positions[idx_spc] + _positions[idx_spn]) / 3.0;
    Eigen::Vector3d avg_hips = (_positions[idx_hipl] + _positions[idx_hipr]) / 2.0;
    Eigen::Vector3d torso = avg_upper - avg_hips;

    // Yhip_vers = (0, 1, 0)
    Eigen::Vector3d Yhip_vers(0, 1, 0);

    // Zhip = (HIPR_x - HIPL_x, 0, HIPR_z - HIPL_z)
    Eigen::Vector3d Zhip(
      _positions[idx_hipr][0] - _positions[idx_hipl][0],
      0,
      _positions[idx_hipr][2] - _positions[idx_hipl][2]
    );
    Eigen::Vector3d Zhip_vers = Zhip.normalized();

    // Xhip_vers = Yhip_vers x Zhip_vers
    Eigen::Vector3d Xhip_vers = Yhip_vers.cross(Zhip_vers);

    // check if Xhip_vers, Yhip_vers, Zhip_vers are ortorhonormal
    double dot_xy = Xhip_vers.dot(Yhip_vers);
    double dot_xz = Xhip_vers.dot(Zhip_vers);
    double dot_yz = Yhip_vers.dot(Zhip_vers);

    // torso_Xhip = dot(torso, Xhip_vers)
    double torso_Xhip = torso.dot(Xhip_vers);
    // torso_Yhip = dot(torso, Yhip_vers)
    double torso_Yhip = torso.dot(Yhip_vers);
    // torso_Zhip = dot(torso, Zhip_vers)
    double torso_Zhip = torso.dot(Zhip_vers);

    // back_flex = arctan(torso_Xhip / torso_Yhip)
    _back_flex = static_cast<float>(std::atan2(torso_Xhip, torso_Yhip) * 180.0 / M_PI);
    // back_bend = arctan(torso_Zhip / torso_Yhip)
    _back_bend = static_cast<float>(std::atan2(torso_Zhip, torso_Yhip) * 180.0 / M_PI);

    // shoulders = SHOR - SHOL
    Eigen::Vector3d shoulders = _positions[idx_shor] - _positions[idx_shol];

    // Zhip_prj = (Zhip_vers_x, Zhip_vers_z)
    Eigen::Vector2d Zhip_prj(Zhip_vers[0], Zhip_vers[2]);
    // shoulders_prj = (shoulders_x, shoulders_z)
    Eigen::Vector2d shoulders_prj(shoulders[0], shoulders[2]);

    double dot_val = Zhip_prj.dot(shoulders_prj);
    double norm_zhip = Zhip_prj.norm();
    double norm_sh = shoulders_prj.norm();
    if (norm_zhip > 1e-6 && norm_sh > 1e-6) {
      double angle = std::acos(std::clamp(dot_val / (norm_zhip * norm_sh), -1.0, 1.0));
      _back_rot = static_cast<float>(angle * 180.0 / M_PI);
    } else {
      _back_rot = 0.0f;
    }

    return return_type::success;
  }


  // Typically, no need to change this
  string kind() override { return PLUGIN_NAME; }

  // Implement the actual functionality here
  return_type load_data(json const &input, string topic = "") override {
    
    // Check if input is of type "FSD" since we only use Merged Skeletons

    // ORIGINALE QUANDO AVREMO LA FUSIONE FUNZIONANTE
    //if (!input.contains("typ") || input["typ"] != "FSD") {
    //_error = "Input data is not a FSD";
    //  cout << _error << endl;
    //  return return_type::retry;
    //}

    // DI PROVA PER TESTARE CON UN HPE SINGOLO
    if (!input.contains("typ") || input["typ"] != "3D") {
      _error = "Input data is not a 3D";
      cout << _error << endl;
      return return_type::retry;
    }

    // store the global timestamp of the input data
    if (input.contains("ts")) {
      _timestamp = input["ts"].get<int64_t>();
    } else {
        _error = "Input data does not contain 'ts'.";
        cout << _error << endl;
        return return_type::retry;
    }

    for (const auto &[label, data] : input.items()) {
      if (data.contains("crd") && data.contains("unc") &&
          data["crd"].is_array() && data["crd"].size() >= 3 &&
          data["unc"].is_array() && data["unc"].size() >= 6) {
        int joint_index = keypoints_map_string2int[label]; // joint index
        _positions[joint_index] = Eigen::Vector3d(data["crd"][0], data["crd"][1], data["crd"][2]) / 1000.0; // convert from mm to m

        Eigen::Matrix3d covariance_matrix = Eigen::Matrix3d::Zero();
        covariance_matrix << data["unc"][0], data["unc"][3], data["unc"][4],
                             data["unc"][3], data["unc"][1], data["unc"][5],
                             data["unc"][4], data["unc"][5], data["unc"][2];
        _covariances[joint_index] = covariance_matrix; // NOTE: covariance is not used currently and the conversion from mm^2 to m^2 is not applied
        
        /*
        // Print label and values
        cout << label
             << ": [" << _positions[joint_index][0] << ", " << _positions[joint_index][1] << ", " << _positions[joint_index][2] << "]"
             << endl;
        */
        
      }
    }
    return return_type::success;
  }

  // We calculate the average of the last N values for each key and store it
  // into the output json object
  return_type process(json &out) override {
    out.clear();

    // Compute preprocessing steps
    compute_baricenter();
    // std::cout << "COM: [" << _com[0] << ", " << _com[1] << ", " << _com[2] << "]" << std::endl;

    // Compute the postural metrics
    compute_horiz_reach();
    compute_vert_reach();
    compute_cervical_flex();
    compute_stability_margin();
    compute_back_angles();

    // Store the computed metrics into the output json object
    out["horiz_reach_left"] = _horiz_reach_left;
    out["horiz_reach_right"] = _horiz_reach_right;
    out["vert_reach_left"] = _vert_reach_left;
    out["vert_reach_right"] = _vert_reach_right;
    out["cervical_flex"] = _cervical_flex;
    out["stability_margin"] = _stability_margin;
    out["back_rot"] = _back_rot;
    out["back_flex"] = _back_flex;
    out["back_bend"] = _back_bend;
    out["ts"] = _timestamp;

    // This sets the agent_id field in the output json object, only when it is
    // not empty
    if (!_agent_id.empty()) out["agent_id"] = _agent_id;
    return return_type::success;
  }
  
  void set_params(void const *params) override {
    // Call the parent class method to set the common parameters 
    // (e.g. agent_id, etc.)
    Filter::set_params(params);

    // then merge the defaults with the actually provided parameters
    // params needs to be cast to json
    _params.merge_patch(*(json *)params);

    // creates two maps to faciliate indexing the joints by name and index
    for (size_t i = 0; i < joint_map.size(); ++i) {
      keypoints_map_string2int[joint_map[i]] = i;
      keypoints_map_int2string[i] = joint_map[i];
    }

    // initialize the internal vectors based on the number of cameras
    size_t num_joints = joint_map.size();
    _positions.resize(num_joints);
    _covariances.resize(num_joints);

    // then merge the defaults with the actually provided parameters
    // params needs to be cast to json
    _params.merge_patch(*(json *)params);

  }

  // Implement this method if you want to provide additional information
  map<string, string> info() override { 
    // return a map of stringswith additional information about the plugin
    // it is used to print the information about the plugin when it is loaded
    // by the agent
    return {}; 
  };

private:
  // Maps the joint names to their indices
  map<string, int> keypoints_map_string2int;
  map<int, string> keypoints_map_int2string;

  // input data
  int64_t _timestamp = 0; // global timestamp of the input data
  std::vector<Eigen::Vector3d> _positions; // _positions[j] is the position (x,y,z) of the j-th joint.
  std::vector<Eigen::Matrix3d> _covariances;  // _covariances[j] is the covariance matrix of the j-th joint.

  // preprocessing 
  Eigen::Vector3d _com;  // Center of mass (COM) of the joint positions

  // output data
  float _horiz_reach_left = 0.0; // Horizontal reach (left)
  float _horiz_reach_right = 0.0; // Horizontal reach (right)
  float _vert_reach_left = 0.0;  // Vertical reach (left)
  float _vert_reach_right = 0.0;  // Vertical reach (right)
  float _cervical_flex = 0.0; // Cervical flexion
  float _stability_margin = 0.0; // Stability margin
  float _back_rot = 0.0; // Back rotation
  float _back_flex = 0.0; // Back flexion
  float _back_bend = 0.0; // Back bending

};


/*
  ____  _             _             _      _
 |  _ \| |_   _  __ _(_)_ __     __| |_ __(_)_   _____ _ __
 | |_) | | | | |/ _` | | '_ \   / _` | '__| \ \ / / _ \ '__|
 |  __/| | |_| | (_| | | | | | | (_| | |  | |\ V /  __/ |
 |_|   |_|\__,_|\__, |_|_| |_|  \__,_|_|  |_| \_/ \___|_|
                |___/
Enable the class as plugin
*/
INSTALL_FILTER_DRIVER(Postural_metrics_assessmentPlugin, json, json);


/*
                  _       
  _ __ ___   __ _(_)_ __  
 | '_ ` _ \ / _` | | '_ \ 
 | | | | | | (_| | | | | |
 |_| |_| |_|\__,_|_|_| |_|
                          
*/

int main(int argc, char const *argv[])
{
  Postural_metrics_assessmentPlugin plugin;
  json params;
  json all_inputs, input, output;

  // Set the parameters
  plugin.set_params(&params);

  // Set input data
  // read dummy json file
  ifstream input_file("dummy/simulated_hpe_inputs.json");
  if (input_file.is_open()) {
    input_file >> all_inputs;
    input_file.close();
  } else {
    cerr << "Unable to open input file" << endl;
    return 1;
  }

  int input_count = 0;
  for (const auto& input : all_inputs) {
    input_count++;
    cout << "Processing input #" << input_count << endl;

    // Set input data
    plugin.load_data(input);

    // Process data
    plugin.process(output);
    cout << "Output: " << output.dump(2) << endl;
  }

  return 0;
}

